# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.0"
manifest_format = "2.0"
project_hash = "7a57ce14b5cf4e5cda6284eee4ea73260650e280"

[[deps.TestImagesAdding]]
git-tree-sha1 = "38c218edfdc89e9a592f6d73870a4d62777d9be5"
repo-rev = "master"
repo-url = "D:\\Hossein\\Programming\\Julia\\TestImagesAdding.jl"
uuid = "a2912350-5aa0-4f8f-8fb8-34b2c1c1c71e"
version = "1.0.0-DEV"
